baseURL = "https://cloud.marcokwak.com"
title = "Marco Kwak"
theme = "hugo-coder"
languageCode = "en-us"
defaultContentLanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Marco Kwak"
    info = "Solutions and Software Engineer"
    description = "Marco's technical blog"
    keywords = "blog,developer,se,solutions,engineer"
    avatarurl = "/images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "Passionate About Technologies"

    hidecredits = true
    hidecopyright = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/marcosdeseul/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/marco-minsoo-kwak-44367388/"
[[params.social]]
    name = "RSS"
    icon = "fas fa-rss"
    weight = 3
    url = "/index.xml"
    rel = "alternate"
    type = "application/rss+xml"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/articles/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"
